# Generated by Django 5.2 on 2025-04-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_marché', '0004_rename_profile_picture_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
