# Generated by Django 5.2 on 2025-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_marché', '0005_commande_payment_method_commande_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.JSONField(max_length=300),
        ),
    ]
