# Generated by Django 5.2 on 2025-04-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_marché', '0006_alter_commande_items'),
    ]

    operations = [
    ]
