# Generated by Django 5.2 on 2025-04-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_marché', '0008_product_image_url_alter_commande_items_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='commande',
            name='payment_method',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('wave', 'Wave'), ('cash', 'Paiement à la livraison')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
