# Generated by Django 5.2 on 2026-01-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_marché', '0010_newslettersubscriber_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
