"""
Django settings for artisancommerce project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES_DIRS=os.path.join(BASE_DIR, 'templates')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#li0c=56dosw^euu-szdv*hbnn-%il%b6z4hj#5chv!4d77&($'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mon_marché'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'artisancommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'artisancommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_URL = 'http://127.0.0.1:8000' 
# settings.py
# ==================== CONFIGURATION WAVE ====================
# Documentation: https://developer.wave.com
WAVE_API_KEY = 'your_wave_api_key_here'  # À obtenir sur Wave Developer Portal
WAVE_MERCHANT_ID = 'your_merchant_id_here'
WAVE_SECRET_KEY = 'your_secret_key_here'

# Numéro Wave pour recevoir les paiements
WAVE_PAYMENT_NUMBER = '22507687487'  # VOTRE NUMÉRO

# URLs de callback Wave
WAVE_SUCCESS_URL = f'{SITE_URL}/payment/wave/success/'
WAVE_ERROR_URL = f'{SITE_URL}/payment/wave/error/'
WAVE_CALLBACK_URL = f'{SITE_URL}/payment/wave/callback/'

# ==================== CONFIGURATION ORANGE MONEY ====================
ORANGE_MERCHANT_KEY = 'your_orange_merchant_key'
ORANGE_API_TOKEN = 'your_orange_api_token'
ORANGE_CALLBACK_URL = f'{SITE_URL}/payment/orange/callback/'
ORANGE_CANCEL_URL = f'{SITE_URL}/payment/orange/cancel/'
ORANGE_NOTIF_URL = f'{SITE_URL}/payment/orange/notification/'

# ==================== CONFIGURATION EMAIL ====================
# Pour envoyer des emails de confirmation
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kouadionia@gmail.com'
EMAIL_HOST_PASSWORD = 'Thania_akt17'

DEFAULT_FROM_EMAIL = 'Mynia Boutique <noreply@mynia.com>'
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Ajoutez dans settings.py
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'